version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-php-fpm
        ports:
            - "8080:80"
    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-postgres
            - manager-redis
            - storage
            - mailer
    manager-php-cli:
        build:
            context: ./manager/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./manager:/app
            - composer:/root/.composer/cache
        depends_on:
            - manager-postgres
            - manager-redis
            - storage
            - mailer
    manager-node-watch:
        image: node:11.13-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
    manager-node:
        image: node:11.13-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
    manager-postgres:
        image: postgres:11.2-alpine
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
    manager-redis:
        image: redis:3.0-alpine
        volumes:
            - manager-redis:/data
        command: redis-server --requirepass secret

    storage:
        build:
            context: ./storage/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./storage:/app
        ports:
            - "8081:80"
    storage-ftp:
        image: stilliard/pure-ftpd
        environment:
            FTP_USER_NAME: app
            FTP_USER_PASS: secret
            FTP_USER_HOME: /app
        volumes:
            - ./storage/public:/app

    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"

volumes:
    manager-postgres:
    manager-redis:
    composer: