# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Model/User/Entity,Model/Work/Entity,Migrations,Tests,Kernel.php}'

    App\Model\User\Entity\User\UserRepository: ~
    App\Model\Work\Entity\Members\Group\GroupRepository: ~
    App\Model\Work\Entity\Members\Member\MemberRepository: ~
    App\Model\Work\Entity\Projects\Role\RoleRepository: ~
    App\Model\Work\Entity\Projects\Project\ProjectRepository: ~
    App\Model\Work\Entity\Projects\Task\TaskRepository: ~

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Finesse\SwiftMailerDefaultsPlugin\SwiftMailerDefaultsPlugin:
        arguments:
            $defaults:
                from:
                    '%env(MAILER_FROM_EMAIL)%': '%env(MAILER_FROM_NAME)%'
        tags:
            - { name: swiftmailer.default.plugin }

    App\Model\User\Service\ResetTokenizer:
        factory: 'App\Container\Model\User\Service\ResetTokenizerFactory:create'
        arguments: ['PT1H']

    Redis:
        class: Redis
        calls:
            -   method: connect
                arguments:
                    - '%env(REDIS_HOST)%'
            -   method: auth
                arguments:
                    - '%env(REDIS_PASSWORD)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    App\Widget\:
        resource: '../src/Widget'
        tags: ['twig.extension']

    App\Menu\SidebarMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: sidebar }]

    App\Menu\Work\MainMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: work_main }]

    App\Menu\Work\Projects\ProjectMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: work_project }]

    App\Menu\Work\Projects\SettingsMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: work_project_settings }]

    App\Menu\Work\Projects\TaskPresetMenu:
        tags: [{ name: knp_menu.menu_builder, method: build, alias: work_projects_task_presets }]

    Symfony\Component\HttpFoundation\Session\Session:
        alias: Symfony\Component\HttpFoundation\Session\SessionInterface

    cebe\markdown\MarkdownExtra:

    App\Service\Work\Processor\Driver\:
        resource: '../src/Service/Work/Processor/Driver/*Driver.php'
        tags: ['app.twig.work_processor.driver']

    App\Service\Work\Processor\Processor:
        arguments: [!tagged app.twig.work_processor.driver]

    App\Service\Uploader\FileUploader:
        arguments: ['@default.storage', '%env(STORAGE_BASE_URL)%']

    App\Model\EventDispatcher:
        class: App\Event\Dispatcher\MessengerEventDispatcher

    phpcent\Client:
        arguments:
            - '%env(CENTRIFUGO_API_HOST)%/api'
            - '%env(CENTRIFUGO_API_KEY)%'
            - '%env(CENTRIFUGO_SECRET)%'
