parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: -

        url: '%env(resolve:DATABASE_URL)%'

        schema_filter: '~^(?!work_projects_tasks_seq)~'

        types:
            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_email: 'App\Model\User\Entity\User\EmailType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'
            comment_comment_id: 'App\Model\Comment\Entity\Comment\IdType'
            comment_comment_author_id: 'App\Model\Comment\Entity\Comment\AuthorIdType'
            work_members_group_id: 'App\Model\Work\Entity\Members\Group\IdType'
            work_members_member_id: 'App\Model\Work\Entity\Members\Member\IdType'
            work_members_member_email: 'App\Model\Work\Entity\Members\Member\EmailType'
            work_members_member_status: 'App\Model\Work\Entity\Members\Member\StatusType'
            work_projects_role_id: 'App\Model\Work\Entity\Projects\Role\IdType'
            work_projects_role_permissions: 'App\Model\Work\Entity\Projects\Role\PermissionsType'
            work_projects_project_id: 'App\Model\Work\Entity\Projects\Project\IdType'
            work_projects_project_status: 'App\Model\Work\Entity\Projects\Project\StatusType'
            work_projects_project_department_id: 'App\Model\Work\Entity\Projects\Project\Department\IdType'
            work_projects_task_id: 'App\Model\Work\Entity\Projects\Task\IdType'
            work_projects_task_type: 'App\Model\Work\Entity\Projects\Task\TypeType'
            work_projects_task_status: 'App\Model\Work\Entity\Projects\Task\StatusType'
            work_projects_task_file_id: 'App\Model\Work\Entity\Projects\Task\File\IdType'
            work_projects_task_change_id: 'App\Model\Work\Entity\Projects\Task\Change\IdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Comment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Comment/Entity'
                prefix: 'App\Model\Comment\Entity'
                alias: User
            Work:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Work/Entity'
                prefix: 'App\Model\Work\Entity'
                alias: Work
